Add an error to FAQ
kivy/kivy-ios pull request #586
Opened 2021-01-18 09:14 UTC by mvasilkov

The fix for an Xcode path error.

xcrun: error: SDK "iphonesimulator" cannot be located

2021-01-23 09:52 UTC, misl6 commented
Maybe it's better to be more generic about the path?

Developers (especially those who aren't downloading Xcode from the App Store), could have their `XCode.app` somewhere else, or, named in a different way.

2021-01-23 22:11 UTC, mvasilkov commented
Well I guess it's self explanatory, but sure, please change it as you see fit.

2021-01-24 10:41 UTC, misl6 requested changes

2021-01-24 10:41 UTC, misl6 commented on README.md
> +Xcode path is not set up correctly. Run the following command to fix this: `sudo xcode-select --switch /Applications/Xcode.app`
```suggestion
Xcode path is not set up correctly. Run the following command to fix this: `sudo xcode-select --switch <YOUR_XCODEAPP_PATH>` (Change `<YOUR_XCODEAPP_PATH>` to the path that reflects your XCode installation, usually is `/Applications/Xcode.app`)
```

2021-02-01 17:52 UTC, Zen-CODE approved these changes
Thanks :-)

2021-02-01 18:59 UTC, merged