recipes: add new `materialyoucolor` recipe
kivy/kivy-ios pull request #898
Opened 2024-03-14 13:47 UTC by T-Dynamos

Closes #895

2024-03-14 16:44 UTC, mrwulff commented
`(venv) kevinwulff@Kevins-MacBook-Air 3 % toolchain build materialyoucolor                          
[INFO    ] Building with 8 processes, where supported
[INFO    ] Want to build ['materialyoucolor']
[INFO    ] Using the bundled version for recipe 'materialyoucolor'
[INFO    ] Loaded recipe materialyoucolor (depends of ['setuptools'], optional are [])
[INFO    ] Using the bundled version for recipe 'setuptools'
Traceback (most recent call last):
  File "/Users/kevinwulff/3/venv/bin/toolchain", line 8, in <module>
    sys.exit(main())
  File "/Users/kevinwulff/3/venv/lib/python3.10/site-packages/kivy_ios/toolchain.py", line 1670, in main
    ToolchainCL()
  File "/Users/kevinwulff/3/venv/lib/python3.10/site-packages/kivy_ios/toolchain.py", line 1407, in __init__
    getattr(self, args.command)()
  File "/Users/kevinwulff/3/venv/lib/python3.10/site-packages/kivy_ios/toolchain.py", line 1483, in build
    build_recipes(args.recipe, ctx)
  File "/Users/kevinwulff/3/venv/lib/python3.10/site-packages/kivy_ios/toolchain.py", line 1201, in build_recipes
    recipe = Recipe.get_recipe(name, ctx)
  File "/Users/kevinwulff/3/venv/lib/python3.10/site-packages/kivy_ios/toolchain.py", line 1064, in get_recipe
    mod = importlib.import_module(f"kivy_ios.recipes.{name}")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'kivy_ios.recipes.setuptools'
(venv) kevinwulff@Kevins-MacBook-Air 3 % 
 `

getting an error when trying to install

2024-03-14 23:46 UTC, subhashsharma commented
@T-Dynamos - I have  the same issue with your Recipe. I tried the below Recipe:

```
from kivy_ios.toolchain import CythonRecipe

class MaterialyoucolorRecipe(CythonRecipe):
    version = "master"
    url = "https://github.com/T-Dynamos/materialyoucolor-python/archive/{version}.zip"
    depends = ["python3"]
    archs = ["x86_64"]

recipe = MaterialyoucolorRecipe()
```
But I get the same SSL CERTIFICATE error which I am yet to resolve in my Mac's Python env.

2024-03-15 08:39 UTC, AndreMiras requested changes
Thanks for the recipe and the materialyoucolor lib :pray: 
Would you mind making the linter happy so we get past next step of building that recipe from the CI?
```
kivy_ios/recipes/materialyoucolor/__init__.py:3:1: E302 expected 2 blank lines, found 1
kivy_ios/recipes/materialyoucolor/__init__.py:8:1: E305 expected 2 blank lines after class or function definition, found 1
```

2024-03-15 12:11 UTC, T-Dynamos commented
Huh?, I don't understand:
```
Nothing to do. No updated recipes.
```

2024-03-16 11:10 UTC, AndreMiras commented
Thanks for catching it, I'm addressing it in https://github.com/kivy/kivy-ios/pull/900
Let's wait for it to be reviewed/merged so we can rebase yours on top

2024-03-16 12:44 UTC, misl6 commented
#900 has been merged.

@T-Dynamos and @AndreMiras, feel free to rebase / complete the review, I will keep #899 in pending until this PR is merged, and rebase on top of it at the end.

2024-03-16 13:04 UTC, misl6 commented
@T-Dynamos seems you left a few things with unresolved merges.

2024-03-16 13:26 UTC, T-Dynamos commented
@misl6 :) Solved.

2024-03-16 13:43 UTC, T-Dynamos commented
Seems there are some errors, I will fix them and re-request review.

2024-03-16 14:30 UTC, T-Dynamos commented
Sorry I am new to IOS, Is there any `c++_shared` lib in IOS?, as I use this in android:
```python
stl_lib_name = "c++_shared"
```

2024-03-16 17:19 UTC, misl6 commented on kivy_ios/recipes/materialyoucolor/__init__.py
> +    depends = ["hostpython3", "python3"]
```suggestion
    depends = ["hostpython3", "python3"]
    hostpython_prerequisites = ["certifi"]
```

2024-03-16 17:20 UTC, misl6 commented on kivy_ios/recipes/materialyoucolor/__init__.py
> +    depends = ["hostpython3", "python3"]
@T-Dynamos , FYI: this one should fix the build, as you should ensure `certifi` is installed on the `hostpython3` environment.

2024-03-16 17:30 UTC, AndreMiras commented
Hi @T-Dynamos, we've merged the fix, it should hopefully work better.
Would you mind doing a rebase on on master?
```
git pull --rebase upstream master # assuming the remote is called upstream
```

2024-03-17 06:39 UTC, AndreMiras approved these changes
CI is happy, thanks for all the follow ups.
And I appreciate the squashing :pray:

2024-03-17 06:39 UTC, merged