Bug fixes xcassets
kivy/kivy-ios pull request #951
Opened 2024-12-07 08:49 UTC by Novfensec

## Introduction
This pull-request is related to the below bug;
- https://github.com/kivy/kivy-ios/issues/950

## Changes
- Reworked the `_buildimage` function in `kivy_ios.tools.external.xcassets` to build correct image sizes.
- Made an adjustment to stop kivy-ios from overriding user defined assets like `Images.xcassets.AppIcon.appiconset` and `Images.xcassets.LaunchImage.launchimage` if they are already present.
- Test workflow run at https://github.com/Novfensec/Tic-Tac-Toe-Android/actions/runs/12210952062
- Hopefully passing all steps nicely.

**With kivy_ios merging the below pull-requests along with this makes it usable along with `buildozer`**:
- https://github.com/kivy/kivy-ios/pull/946
- https://github.com/kivy/kivy-ios/pull/949

## Testing
- **python**: `3.11`
- **Cython**: `0.29.36`
- **Pillow**: `8.2.0` with old recipe.
- **itsdangerous**: `2.2.0` with latest recipe by the pull-request https://github.com/kivy/kivy-ios/pull/946.
- **buildozer**: `1.5.0`

2024-12-10 08:31 UTC, Novfensec commented
Hey @AndreMiras , I fixed the icon generation issues within the `icon` and `_generate` function. You can test build using branch `patch-2` of https://github.com/Novfensec/kivy-ios/tree/patch-2 .

```bash
buildozer -v ios debug
```

2024-12-10 09:29 UTC, AndreMiras commented
Thank you for spending time on that one :pray: 
Would you mind editing the PR to not touch the formatting and address only the bug you mentioned in `_buildimage()`
Honestly I wish we had a formatter in the CI so it didn't have to be a recurring topic

2024-12-10 09:37 UTC, Novfensec commented
> Thank you for spending time on that one :pray: 
> Would you mind editing the PR to not touch the formatting and address only the bug you mentioned in `_buildimage()`
> Honestly [I wish we had a formatter](https://github.com/kivy/python-for-android/issues/1950) in the CI so it didn't have to be a recurring topic

I used black for formatting. So, I'll just realign the list back to their original style. Please wait!!

2024-12-10 09:43 UTC, Novfensec commented
@AndreMiras Reverted Dict formatting to original.

2025-01-02 11:10 UTC, misl6 reviewed
@Novfensec I see we still have some indentation that breaks the original style, can you please take a look?

2025-01-02 11:23 UTC, Novfensec commented
Ahhh. Sorry for that I just overlooked, just a minute!!

2025-01-02 11:32 UTC, Novfensec commented
> @Novfensec I see we still have some indentation that breaks the original style, can you please take a look?

@misl6 
Now is it okay?? All other changes are made to fix the overall process of generating images and icons nicely if there is no predefined Images.xcassets folder from the user side.

2025-01-06 11:45 UTC, misl6 commented on kivy_ios/tools/external/xcassets.py
> +        _generate("LaunchImage.launchimage", image_xcassets, image_fn, options)
What happens if the directory already exists? Should not the `LauchImage.launchimage` be generated again?

2025-01-06 13:04 UTC, Novfensec commented on kivy_ios/tools/external/xcassets.py
> +        _generate("LaunchImage.launchimage", image_xcassets, image_fn, options)
I just indented this whole bunch to come under the if block which checks if the directory is present or not then do the task;
The same for `Appicon.appiconset`;

The final code looks like below;
```python
def launchimage(image_xcassets, image_fn):
    """Generate all the possible Launch Images from a single image_fn"""
    launchimage_dir = join(image_xcassets, "LaunchImage.launchimage")
    if not exists(launchimage_dir):
        makedirs(launchimage_dir)
        with open(join(launchimage_dir, "Contents.json"), "w") as fd:
            json.dump(launchimage_json, fd)

        options = (
            # size, input, output
            # iPhone 3.5" @2x
            ("640 960", None, "Default640x960.png"),
            # iPhone 3.5" @1x
            ("320 480", None, "Default320x480.png"),
            # iPhone 4.0" @2x
            ("640 1136", None, "Default640x1136.png"),
            # iPhone 5.5" @3x - landscape
            ("2208 1242", None, "Default2208x1242.png"),
            # iPhone 5.5" @3x - portrait
            ("1242 2208", None, "Default1242x2208.png"),
            # iPhone 4.7" @2x
            ("750 1334", None, "Default750x1334.png"),
            # iPad @2x - landscape
            ("2048 1536", None, "Default2048x1536.png"),
            # iPad @2x - portrait
            ("1536 2048", None, "Default1536x2048.png"),
            # iPad @1x - landscape
            ("1024 768", None, "Default1024x768.png"),
            # iPad @1x - portrait
            ("768 1024", None, "Default768x1024.png"),
        )

        _generate("LaunchImage.launchimage", image_xcassets, image_fn, options)
```
It clearly says if there is no `Launchimage.launchimage` then only make it and generate other files.

**At present it looks for two directories namely `Appicon.appiconset` and `Launchimage.launchimage` under `Images.xcassets`. If they are already present it skips them elsewise makes the dirs and files.**

2025-01-06 13:34 UTC, misl6 commented on kivy_ios/tools/external/xcassets.py
> +        _generate("LaunchImage.launchimage", image_xcassets, image_fn, options)
It makes sense to me, thank you!

2025-01-06 13:46 UTC, misl6 requested changes
From your explanation I got what we're trying to achieve and how we can make the appropriate changes.

kivy-ios overriding the generated files is not necessarily a bug, actually that could be a wanted feature (or at least now is an undocumented feature that someone might be taking advantage of).

But, I also agree that in certain cases (like when used in buildozer automations) kivy-ios overriding user-defined assets might be unexpected.

Can we split the PRs in two parts?
- Fix correct image sizes
- Allow through a flag to not overwrite an already-existing asset (defaults to overwrite for backward compatibility)

Then, in buildozer, feel free to open a PR which adds an option to not overwrite an existing asset.

2025-01-06 13:53 UTC, Novfensec commented
> From your explanation I got what we're trying to achieve and how we can make the appropriate changes.
> 
> kivy-ios overriding the generated files is not necessarily a bug, actually that could be a wanted feature (or at least now is an undocumented feature that someone might be taking advantage of).
> 
> But, I also agree that in certain cases (like when used in buildozer automations) kivy-ios overriding user-defined assets might be unexpected.
> 
> Can we split the PRs in two parts?
> - Fix correct image sizes
> - Allow through a flag to not overwrite an already-existing asset (defaults to overwrite for backward compatibility)
> 
> Then, in buildozer, feel free to open a PR which adds an option to not overwrite an existing asset.

Yes, so should I unindent the code blocks or you'll undo those changes after merging, and make a new pull ??

2025-03-11 02:31 UTC, Novfensec commented
@misl6 After a lot more thinking I concluded that we will never require a flag atleast for now beacuse most of the kivy-ios users don't even know that we have to provide a set of icons for all apple platforms. As you suggested this is a fantastic feature provided by kivy-ios. I reverted the changes by unindenting those code blocks to their original style. Now they will build a set of icons without interruption. But before a final merge I want to reexamine these changes by building a test app to see if it doesn't crash. I will inform with the appropriate link.

Please leave your thoughts!!!

2025-03-11 06:15 UTC, Novfensec commented
@AndreMiras and @misl6 Sorry for pinging everytime. I tested with the updated `xcassets.py` setup again and there was no error related to xcassets during the build. Below is the link for the github run on the latest mascos runner image.
- https://github.com/Novfensec/Tic-Tac-Toe-Android/actions/runs/13779646844

The run used a custom fork of kivy-ios with bug fixes related to ios deploy target and xcassets only.

2026-04-18 02:49 UTC, closed without merging